package app

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/Bel-Consulting-OU/kiwi-ci/internal/importer"
	"github.com/Bel-Consulting-OU/kiwi-ci/internal/pipeline"
)

// placeholderDigest is the pinned-image placeholder written into generated
// starters. It is deliberately not a real image: users must replace it
// before running, as the generated comment instructs.
const placeholderDigest = "sha256:0000000000000000000000000000000000000000000000000000000000000000"

// Init implements `kiwi init`: it detects the project language from marker
// files and writes a starter .kiwi/pipeline.yaml tailored to it. An
// existing pipeline file is never overwritten without --force.
func Init(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	force := fs.Bool("force", false, "overwrite an existing pipeline file")
	output := fs.String("f", ".kiwi/pipeline.yaml", "output pipeline file")
	dir := fs.String("dir", ".", "project directory to inspect")
	if err := fs.Parse(args); err != nil {
		return err
	}
	wd, err := filepath.Abs(*dir)
	if err != nil {
		return err
	}
	lang, tool := detectLanguage(wd)
	if lang == "" {
		return fmt.Errorf("no supported language detected in %s (looked for go.mod, package.json, pnpm-lock.yaml, yarn.lock, Cargo.toml, pyproject.toml, uv.lock, poetry.lock, Package.swift, *.xcodeproj, *.xcworkspace, pom.xml, build.gradle)", wd)
	}
	spec := starterSpec(lang, tool)
	body, err := importer.MarshalSpec(spec)
	if err != nil {
		return err
	}
	doc := fmt.Sprintf("# Generated by `kiwi init` (detected language: %s).\n# IMPORTANT: every image below is pinned to a placeholder digest.\n# Replace each @%s with a real pinned digest (e.g. `docker buildx imagetools inspect <image>`)\n# so jobs cannot be swapped by mutable image tags.\n%s", lang, placeholderDigest, body)
	target := filepath.Join(wd, *output)
	if _, err := os.Stat(target); err == nil && !*force {
		return fmt.Errorf("%s already exists; use --force to overwrite", target)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(doc), 0o644); err != nil {
		return err
	}
	fmt.Printf("detected %s; wrote %s\n", lang, target)
	return nil
}

// detectLanguage inspects dir for well-known project markers and returns
// the language and its toolchain detail (npm/yarn/pnpm, pip/uv/poetry,
// maven/gradle). Precedence: go, rust, swift, jvm, python, node.
func detectLanguage(dir string) (lang, tool string) {
	exists := func(name string) bool {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			return true
		}
		return false
	}
	matches := func(pattern string) bool {
		files, _ := filepath.Glob(filepath.Join(dir, pattern))
		return len(files) > 0
	}
	switch {
	case exists("go.mod"):
		return "go", ""
	case exists("Cargo.toml"):
		return "rust", ""
	case exists("Package.swift") || matches("*.xcodeproj") || matches("*.xcworkspace"):
		return "swift", ""
	case exists("pom.xml"):
		return "jvm", "maven"
	case exists("build.gradle") || exists("build.gradle.kts"):
		return "jvm", "gradle"
	case exists("pyproject.toml") || exists("uv.lock") || exists("poetry.lock"):
		switch {
		case exists("uv.lock"):
			return "python", "uv"
		case exists("poetry.lock"):
			return "python", "poetry"
		default:
			return "python", "pip"
		}
	case exists("pnpm-lock.yaml"):
		return "node", "pnpm"
	case exists("yarn.lock"):
		return "node", "yarn"
	case exists("package.json"):
		return "node", "npm"
	}
	return "", ""
}

// starterSpec builds the language-specific starter pipeline.
func starterSpec(lang, tool string) *pipeline.Spec {
	switch lang {
	case "go":
		return goStarter()
	case "node":
		return nodeStarter(tool)
	case "rust":
		return rustStarter()
	case "python":
		return pythonStarter(tool)
	case "swift":
		return swiftStarter()
	case "jvm":
		return jvmStarter(tool)
	}
	return &pipeline.Spec{Version: 1, Jobs: map[string]pipeline.Job{}}
}

func containerJob(name, image string) pipeline.Job {
	return pipeline.Job{Runtime: "container", Image: image + "@" + placeholderDigest}
}

func goStarter() *pipeline.Spec {
	quality := containerJob("quality", "golang:1.23")
	quality.Steps = []pipeline.Step{
		{Name: "gofmt", Run: `test -z "$(gofmt -l .)"`},
		{Name: "vet", Run: "go vet ./..."},
	}
	test := containerJob("test", "golang:1.23")
	test.Needs = []string{"quality"}
	test.Cache = []pipeline.Cache{{Name: "go-cache", Paths: []string{".kiwi/go-cache"}, HashFiles: []string{"go.sum"}}}
	test.Steps = []pipeline.Step{
		{Name: "build", Run: "go build ./..."},
		{Name: "test", Run: "go test ./..."},
	}
	return &pipeline.Spec{Version: 1, Name: "go-ci", Env: map[string]string{"GOCACHE": ".kiwi/go-cache"}, Jobs: map[string]pipeline.Job{"quality": quality, "test": test}}
}

func nodeStarter(pkgManager string) *pipeline.Spec {
	install := containerJob("install", "node:20")
	lockfile := "package-lock.json"
	installCmd := "npm ci"
	switch pkgManager {
	case "yarn":
		lockfile = "yarn.lock"
		installCmd = "yarn install --frozen-lockfile"
	case "pnpm":
		lockfile = "pnpm-lock.yaml"
		installCmd = "pnpm install --frozen-lockfile"
	}
	install.Cache = []pipeline.Cache{{Name: "node-modules", Paths: []string{"node_modules"}, HashFiles: []string{lockfile}}}
	install.Steps = []pipeline.Step{
		{Name: "install", Run: installCmd},
		{Name: "build", Run: "npm run build"},
	}
	test := containerJob("test", "node:20")
	test.Needs = []string{"install"}
	test.Cache = []pipeline.Cache{{Name: "node-modules", Paths: []string{"node_modules"}, HashFiles: []string{lockfile}}}
	test.Steps = []pipeline.Step{{Name: "test", Run: "npm test"}}
	return &pipeline.Spec{Version: 1, Name: "node-ci", Jobs: map[string]pipeline.Job{"install": install, "test": test}}
}

func rustStarter() *pipeline.Spec {
	quality := containerJob("quality", "rust:1.83")
	quality.Steps = []pipeline.Step{
		{Name: "fmt", Run: "cargo fmt --check"},
		{Name: "clippy", Run: "cargo clippy -- -D warnings"},
	}
	test := containerJob("test", "rust:1.83")
	test.Needs = []string{"quality"}
	test.Cache = []pipeline.Cache{{Name: "cargo-target", Paths: []string{"target"}, HashFiles: []string{"Cargo.lock"}}}
	test.Steps = []pipeline.Step{
		{Name: "build", Run: "cargo build"},
		{Name: "test", Run: "cargo test"},
	}
	return &pipeline.Spec{Version: 1, Name: "rust-ci", Jobs: map[string]pipeline.Job{"quality": quality, "test": test}}
}

func pythonStarter(tool string) *pipeline.Spec {
	quality := containerJob("quality", "python:3.12")
	test := containerJob("test", "python:3.12")
	test.Needs = []string{"quality"}
	test.Cache = []pipeline.Cache{{Name: "venv", Paths: []string{".venv"}, HashFiles: []string{"requirements.txt", "pyproject.toml"}}}
	switch tool {
	case "uv":
		quality.Steps = []pipeline.Step{{Name: "check", Run: "uv sync --frozen && uv run ruff check ."}}
		test.Steps = []pipeline.Step{{Name: "pytest", Run: "uv sync --frozen && uv run pytest"}}
	case "poetry":
		quality.Steps = []pipeline.Step{{Name: "check", Run: "poetry install --no-interaction && poetry run ruff check ."}}
		test.Steps = []pipeline.Step{{Name: "pytest", Run: "poetry install --no-interaction && poetry run pytest"}}
	default:
		quality.Steps = []pipeline.Step{{Name: "check", Run: "python -m venv .venv && .venv/bin/pip install ruff && .venv/bin/ruff check ."}}
		test.Steps = []pipeline.Step{{Name: "pytest", Run: "python -m venv .venv && .venv/bin/pip install -e . && .venv/bin/pytest"}}
	}
	return &pipeline.Spec{Version: 1, Name: "python-ci", Jobs: map[string]pipeline.Job{"quality": quality, "test": test}}
}

func swiftStarter() *pipeline.Spec {
	// xcodebuild and swift test require macOS; the tart VM is a placeholder
	// the header comment instructs users to pin.
	build := pipeline.Job{
		Name: "xcode-build", Runtime: "tart",
		VM: "ghcr.io/cirruslabs/macos-tahoe-base:latest",
		Steps: []pipeline.Step{
			{Name: "xcodebuild", Run: `xcodebuild -scheme "${SCHEME:-$(xcodebuild -list -json | sed -n 's/.*"name" : "\([^"]*\)".*/\1/p' | head -1)}" build`},
			{Name: "swift-test", Run: "swift test"},
		},
	}
	return &pipeline.Spec{Version: 1, Name: "swift-ci", Jobs: map[string]pipeline.Job{"xcode-build": build}}
}

func jvmStarter(tool string) *pipeline.Spec {
	build := containerJob("build", "maven:3.9-eclipse-temurin-21")
	build.Cache = []pipeline.Cache{{Name: "m2", Paths: []string{".m2"}}}
	build.Steps = []pipeline.Step{{Name: "verify", Run: "mvn -B verify"}}
	if tool == "gradle" {
		build = containerJob("build", "gradle:8-jdk21")
		build.Cache = []pipeline.Cache{{Name: "gradle-home", Paths: []string{".gradle"}}}
		build.Steps = []pipeline.Step{{Name: "build", Run: "./gradlew build"}}
	}
	return &pipeline.Spec{Version: 1, Name: "jvm-ci", Jobs: map[string]pipeline.Job{"build": build}}
}
