// Command filemap generates FILE_MAP.md, a deterministic inventory of the
// repository: one table row per file with the file path and a short
// description derived from the file's first doc comment line (Go, SQL) or
// first heading/comment (Markdown, YAML, TOML, JSON), with small fallbacks
// for known file kinds. Output is sorted byte-wise by path, excluding the
// .git, dist, and tmp directories.
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	maxDescription = 120
	outputName     = "FILE_MAP.md"
)

func main() {
	root := flag.String("root", ".", "repository root to walk")
	out := flag.String("out", "", "output path (default: <root>/FILE_MAP.md)")
	check := flag.Bool("check", false, "fail if FILE_MAP.md is stale instead of writing")
	flag.Parse()

	abs, err := filepath.Abs(*root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "filemap:", err)
		os.Exit(1)
	}
	dest := *out
	if dest == "" {
		dest = filepath.Join(abs, outputName)
	}

	var paths []string
	err = filepath.WalkDir(abs, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, rerr := filepath.Rel(abs, p)
		if rerr != nil {
			return rerr
		}
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "dist", "tmp", "vendor", "testdata":
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == outputName && rel == outputName {
			return nil
		}
		if skipFile(rel, d) {
			return nil
		}
		paths = append(paths, rel)
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "filemap:", err)
		os.Exit(1)
	}
	sort.Strings(paths)

	var b strings.Builder
	fmt.Fprintf(&b, "# Kiwi CI file map\n\n")
	fmt.Fprintf(&b, "This file map is generated by `go run ./cmd/filemap`. It lists **%d files**.\n\n", len(paths))
	b.WriteString("| File | What it contains |\n")
	b.WriteString("|---|---|\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "| `%s` | %s |\n", p, describe(p, filepath.Join(abs, filepath.FromSlash(p))))
	}
	generated := b.String()
	if *check {
		existing, rerr := os.ReadFile(dest)
		if rerr == nil && string(existing) == generated {
			fmt.Printf("filemap: %s is up to date (%d files)\n", dest, len(paths))
			return
		}
		fmt.Fprintf(os.Stderr, "filemap: %s is stale; run `go run ./cmd/filemap` to regenerate\n", dest)
		os.Exit(1)
	}
	if err := os.WriteFile(dest, []byte(generated), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "filemap:", err)
		os.Exit(1)
	}
	fmt.Printf("filemap: wrote %s (%d files)\n", dest, len(paths))
}

// skipFile filters out generated metadata and non-source artifacts that must
// not appear in the inventory.
func skipFile(rel string, d fs.DirEntry) bool {
	name := d.Name()
	if name == ".DS_Store" || name == "Thumbs.db" || name == "desktop.ini" {
		return true
	}
	if strings.HasSuffix(name, ".tmp") || strings.HasSuffix(name, ".prof") || strings.HasSuffix(name, ".out") {
		return true
	}
	if rel == "go.sum" {
		return false
	}
	if info, err := d.Info(); err == nil && info.Mode().IsRegular() {
		if b, rerr := os.ReadFile(filepath.Join(".", filepath.FromSlash(rel))); rerr == nil && !isText(b) {
			return true
		}
	}
	return false
}

// isText reports whether the buffer looks like human-readable text (UTF-8
// with printable content) rather than a binary artifact.
func isText(b []byte) bool {
	if len(b) == 0 {
		return true
	}
	n := len(b)
	if n > 512 {
		n = 512
	}
	for _, c := range b[:n] {
		if c == 0 {
			return false
		}
	}
	return true
}

// describe returns a short, single-line description for the file at path
// abs, derived from its first doc comment line or heading.
func describe(rel, abs string) string {
	if rel == "FILE_MAP.md" {
		return "Generated inventory of every file in the repository (this file)."
	}
	data, err := os.ReadFile(abs)
	if err != nil {
		return "File could not be read."
	}
	content := string(data)
	desc := ""
	switch {
	case strings.HasSuffix(rel, ".go"):
		desc = firstGoDocComment(content)
	case strings.HasSuffix(rel, ".md"):
		desc = firstHeadingOrLine(content)
	case strings.HasSuffix(rel, ".sql"):
		desc = firstCommentOrLine(content, "--")
	case strings.HasSuffix(rel, ".yaml") || strings.HasSuffix(rel, ".yml") || strings.HasSuffix(rel, ".toml"):
		desc = firstCommentOrLine(content, "#")
	case strings.HasSuffix(rel, ".json"):
		desc = firstNonEmpty(content)
	case rel == "LICENSE":
		desc = firstNonEmpty(content)
	case rel == "Makefile":
		desc = firstCommentOrLine(content, "#")
	case rel == ".gitignore":
		desc = firstUncommentedLine(content, "#")
	default:
		desc = firstNonEmpty(content)
	}
	if desc == "" {
		desc = fallbackDescription(rel)
	}
	desc = strings.Join(strings.Fields(desc), " ")
	desc = strings.ReplaceAll(desc, "|", `\|`)
	if len(desc) > maxDescription {
		desc = desc[:maxDescription-3] + "..."
	}
	return desc
}

// firstGoDocComment returns the first line of the leading doc comment block
// above the package clause.
func firstGoDocComment(s string) string {
	lines := strings.Split(s, "\n")
	var comment []string
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if t == "" {
			continue
		}
		if strings.HasPrefix(t, "//") {
			comment = append(comment, strings.TrimSpace(strings.TrimPrefix(t, "//")))
			continue
		}
		if strings.HasPrefix(t, "/*") {
			comment = append(comment, strings.TrimSpace(strings.TrimPrefix(t, "/*")))
			continue
		}
		// A non-comment line (including the package clause) ends the doc block.
		break
	}
	if len(comment) == 0 {
		return ""
	}
	return comment[0]
}

// firstHeadingOrLine returns the first Markdown heading, or the first
// non-empty line when there is none.
func firstHeadingOrLine(s string) string {
	for _, l := range strings.Split(s, "\n") {
		t := strings.TrimSpace(l)
		if t == "" {
			continue
		}
		if strings.HasPrefix(t, "#") {
			return strings.TrimSpace(strings.TrimLeft(t, "#"))
		}
		return t
	}
	return ""
}

// firstCommentOrLine returns the first comment line (stripped of the given
// comment marker), or the first non-empty line when there is none.
func firstCommentOrLine(s, marker string) string {
	var first string
	for _, l := range strings.Split(s, "\n") {
		t := strings.TrimSpace(l)
		if t == "" {
			continue
		}
		if first == "" {
			first = t
		}
		if strings.HasPrefix(t, marker) {
			return strings.TrimSpace(strings.TrimPrefix(t, marker))
		}
	}
	return first
}

// firstUncommentedLine returns the first non-empty line that does not start
// with the given marker.
func firstUncommentedLine(s, marker string) string {
	for _, l := range strings.Split(s, "\n") {
		t := strings.TrimSpace(l)
		if t == "" || strings.HasPrefix(t, marker) {
			continue
		}
		return t
	}
	return ""
}

// firstNonEmpty returns the first non-empty, trimmed line.
func firstNonEmpty(s string) string {
	for _, l := range strings.Split(s, "\n") {
		if t := strings.TrimSpace(l); t != "" {
			return t
		}
	}
	return ""
}

// fallbackDescription provides a directory-based description when a file has
// no usable header line.
func fallbackDescription(rel string) string {
	dir := filepath.Dir(rel)
	switch {
	case strings.HasSuffix(rel, "_test.go"):
		return "Regression tests for the " + filepath.Base(dir) + " package."
	case strings.HasSuffix(rel, ".go"):
		return "Go source in internal/" + filepath.Base(dir) + "."
	case strings.HasSuffix(rel, ".md"):
		return "Documentation file."
	case strings.HasSuffix(rel, ".yaml") || strings.HasSuffix(rel, ".yml"):
		return "YAML configuration file."
	case strings.HasSuffix(rel, ".json"):
		return "JSON data file."
	default:
		return "Repository file."
	}
}
